### ISSUE TITLE
tmap and bcmaps issue

### ISSUE THREAD

**Issue by hgriesbauer** [bcgov/bcmaps#100]
Hello!  I get an error message when I try and run the following code.  I can't make any headway on figuring this out.  Any suggestions?

bc_bound() %>% 
  tm_shape()+
  tm_polygons(col="lightblue")

The error message:  Error: Assigned data `NA` must be compatible with existing data.
i Error occurred for column `COLOR_1`.
x Can't convert <logical> to <character>.

The code works if I omit the color parameter.  I think the issue is with the bc_bound sf object.

**Comment by hgriesbauer** [comment]
Forgot to say thanks in advance!

**Comment by stephhazlitt** [comment]
Thanks @hgriesbauer, can you provide your session details with package versions?

**Comment by stephhazlitt** [comment]
``` r
library(bcmaps)
#> Loading required package: sf
#> Linking to GEOS 3.9.1, GDAL 3.2.3, PROJ 7.2.1; sf_use_s2() is TRUE
library(tmap)

bc_bound() |> 
  tm_shape() +
  tm_polygons(col="lightblue")
#> bc_bound_hres was updated on 2021-12-11
```

![](https://i.imgur.com/LTyUjNy.png)

<sup>Created on 2022-01-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hgriesbauer** [comment]
HI @stephhazlitt thanks for the prompt reply!  I updated my tmap and bcmaps packages, and it works now.  Thanks again!
