### ISSUE TITLE
habc rasters

### ISSUE THREAD

**Issue by dfilatow** [bcgov/bcmaps#107]
The hectares BC application is being decommissioned June 15, 2022. There are raster in that dataset that would be very useful in the bcmaps package. Ones we contributed include Parent Material (Bulmer etal. 2016) and some of the layers that went into that map including MRVB and RHS. I also believe the Grassland and Wetland layers would be useful. I don't know who owns it but the elevation/slope/aspect would be a welcome addition. Is this a possibility?

**Comment by ateucher** [comment]
Hi @dfilatow, thanks for the heads up - I didn't know HectaresBC was being decomissioned! I don't think bcmaps is the right place to maintain access to these important layers, as it's only an R package so it would restrict usage to R users. Also an R package is never a good solution for long-term archival and hosting of data - it should just be pointing to existing datasets to provide access to R users. The ideal solution would be for those layers to be accessible through the BC Data Catalogue and then packages like bcmaps/bcdata could access them.

**Comment by stephhazlitt** [comment]
@dfilatow @ateucher I am closing this issue, however feel free to re-open if further discussion is warranted.
