### ISSUE TITLE
Deprecate support for sp

### ISSUE THREAD

**Issue by ateucher** [bcgov/bcmaps#109]
As these are end-of-life and being fully replaced by sf and terra, we should drop support for them, first by deprecating, then by removing them entirely

**Comment by stephhazlitt** [comment]
Would we consider using [lifecycle](https://lifecycle.r-lib.org/index.html) for this, it has a nice option to deprecate just an argument or partially deprecate an argument. On quick look this is what we will need to do for most of the functions for `sp`?

**Comment by ateucher** [comment]
I think for the functions that provide data sources that makes sense... basically want to deprecate the `class` parameter right? For the utility functions (`fix_geo_problems`, `transform_bc_albers`) we want to deprecate the `.Spatial` methods I think using the [traditional means](https://devguide.ropensci.org/evolution.html#functions-deprecate-defunct) - but I bet Lifecycle has ways to facilitate that as well?

**Comment by boshek** [comment]
One other way would be to just add a message on package load saying "sp is going away, be advised". The advantage there is that it is more likely to be read. Or maybe a combination of the two.

**Comment by ateucher** [comment]
I think both are a good idea. Using the `.Depracated` method you get the message on the function calls "for free"

**Comment by stephhazlitt** [comment]
This issue includes a fair bit of documentation updating as well. Perhaps just a notice for deprecating, but quite a bit of editing with removal.

**Comment by ateucher** [comment]
For sure. Should check the vignettes as wel

**Comment by stephhazlitt** [comment]
I have a [PR up starting this work](https://github.com/bcgov/bcmaps/pull/119).  Should (or can) we duplicate this issue and have one Issue/PR for deprecating all `sp`-related functionality and a second Issue/PR for changing raster fxns to use {terra}?

**Comment by stephhazlitt** [comment]
@ateucher _nudge_ re: splitting this work behind this out into 2 PRs?

**Comment by ateucher** [comment]
I think two PRs makes sense

**Comment by stephhazlitt** [comment]
@ateucher Do we leave this open until the Summer release?

**Comment by ateucher** [comment]
Let's close it - I'll change the name so it's more reflective of what we did, then open a new one with a milestone

**Comment by ateucher** [comment]
closed by #119
