### ISSUE TITLE
how to remove yes/no prompts on data storage

### ISSUE THREAD

**Issue by klwilson23** [bcgov/bcmaps#112]
After my most recent updating of R and associated libraries, I am getting a lot of yes/no prompts from bcmaps() for storing data:

```
bec <- bcmaps::bec()
bcmaps would like to store this layer in the directory:
~Local/R/cache/R/bcmaps
Is that okay?
1: Yes
2: No
```

This prompt is quite disruptive to my workflows and prevents me from automatically running or re-running my R scripts for spatial analyses, etc. 

Is there a way to simply automatically answer 'yes' to this question? I haven't seen these prompts come up before, but I am working on a new computer so perhaps these questions go away after a while.

**Comment by boshek** [comment]
👋 @klwilson23 

Each bcmaps function should have an `ask` parameter to skip this step. It is just that the default is to ask. Try:

```r
bec <- bcmaps::bec(ask = FALSE)
```

**Comment by stephhazlitt** [comment]
Just FYI, setting the default `ask = TRUE` is intentional, as it is considered a no-go/impolite for software to save something to a users machine without asking.

**Comment by klwilson23** [comment]
Fantastic! Thank you for the help @boshek, and totally understand about the default choice @stephhazlitt.
