### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [bcgov/bcmaps#117]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by ateucher** [comment]
Related to #109

**Comment by ateucher** [comment]
Thanks for this! We will start to implement this soon, switching to terra where necessary, combined with some deprecation.

**Comment by ateucher** [comment]
This is closed by #119 - we've deprecated most of the functionality using `sp` and `raster` (and all using rgdal or rgeos), and will fully remove all use of rgeos and rgdal in the summer. In the meantime we've removed all tests and examples that require `rgdal` or `rgeos`, so with `SP_EVOLUTION_STATUS=2, and without `rgeos` and `rgdal` on the library path, I get all clean checks.

**Comment by rsbivand** [comment]
`rgdal` and `rgeos` are still `Suggests:`. Three months left to remove them.

**Comment by ateucher** [comment]
This is done now with v2.0.0
