### ISSUE TITLE
Drop sp support

### ISSUE THREAD

**Issue by ateucher** [bcgov/bcmaps#123]
- [ ] make `class` argument defunct
- [ ] make utility functions marked as `deprecated` defunct
- [ ] remove rgdal and rgeos from suggests
- [ ] ...?

**Comment by ateucher** [comment]
We will continue to support raster as it has switched the underlying engine from rgdal/rgeos to sf and terra

**Comment by stephhazlitt** [comment]
@ateucher @boshek should we set ourselves a target date for this issue ([we have 3 months tops](https://github.com/bcgov/bcmaps/issues/117#issuecomment-1623757452))?

**Comment by ateucher** [comment]
Yep, how about Aug 31?
