### ISSUE TITLE
Missing part of map in airzone()

### ISSUE THREAD

**Issue by jeromerobles** [bcgov/bcmaps#129]
Georgia Strait seems to be missing in the airzones() function. 

`plot(bcmaps::airzones())`

**Comment by stephhazlitt** [comment]
I can reproduce this issue @jeromerobles. Let me source the data directly from the catalogue to confirm it is not a data source issue as a first step.

**Comment by stephhazlitt** [comment]
Works fine with `bcdata` (which is the package `bcmaps` uses under the hood to source the data from the B.C. Data Catalogue) so this is indeed a bug in `bcmaps`. 


``` r
#use bcmaps -- missing a zone
plot(bcmaps::airzones())
#> airzones was updated on NULL
```

![](https://i.imgur.com/DWLNoaZ.png)

``` r

#use bcdata to get shp file -- all zones
plot(bcdata::bcdc_get_data(record = 'e8eeefc4-2826-47bc-8430-85703d328516', 
                            resource = '4cea4b22-36a3-4ea7-9346-7e872e747076'))
#> Reading the data using the read_sf function from the sf package.
```

![](https://i.imgur.com/VEfguhp.png)

``` r

#use bcdata to get geojson file -- all zones
plot(bcdata::bcdc_get_data(record =
                'e8eeefc4-2826-47bc-8430-85703d328516', resource =
                'c495d082-b586-4df0-9e06-bd6b66a8acd9'))
#> Reading the data using the read_sf function from the sf package.
```

![](https://i.imgur.com/nqmEFir.png)

<sup>Created on 2023-07-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by boshek** [comment]
I think this might be a caching issue. If you tried running:

```r
 bcmaps::delete_cache("airzones.rds")
 ```
 
 and then re-running it again, what happens? For me that fixes this.

**Comment by stephhazlitt** [comment]
I did start with a fresh pull using `bcmaps` (I should have included that above, sorry). No luck for me:

``` r
bcmaps::delete_cache("airzones.rds")
plot(bcmaps::airzones())
#> Saving to bcmaps data directory at /Users/stephhazlitt/Library/Caches/org.R-project.R/R/bcmaps
#> Reading the data using the read_sf function from the sf package.
```

![](https://i.imgur.com/bYQnIp7.png)

<sup>Created on 2023-07-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by boshek** [comment]
> I did start with a fresh pull using bcmaps

I should've done the same. Can reproduce now. It was _my_ cache that was invalidated 🤦

**Comment by boshek** [comment]
Something weird in the raw data so probably an upstream catalogue issue. I mean it is still there, just not plotting.

``` r
library(bcmaps)
#> Loading required package: sf
#> Linking to GEOS 3.11.0, GDAL 3.5.3, PROJ 9.1.0; sf_use_s2() is TRUE
#> Support for Spatial objects (`sp`) was deprecated in {bcmaps} v1.2.0, and will be removed altogether in the Summer 2023. Please use `sf` objects with {bcmaps}.
raw_airzones <- airzones()
#> airzones was updated on NULL

plot(raw_airzones)
```

![](https://i.imgur.com/fglgLBD.png)

``` r

(coastal_airzones <- raw_airzones[raw_airzones$Airzone %in% c("Coastal", "Northwest"), ])
#> Simple feature collection with 2 features and 1 field
#> Geometry type: GEOMETRY
#> Dimension:     XY
#> Bounding box:  xmin: 272458 ymin: 654672.7 xmax: 1196788 ymax: 1735332
#> Projected CRS: NAD83 / BC Albers
#> # A tibble: 2 × 2
#>   Airzone                                                               geometry
#>   <chr>                                                           <GEOMETRY [m]>
#> 1 Northwest POLYGON ((272458 1735332, 365988.2 1719589, 515080.9 1697364, 62991…
#> 2 Coastal   MULTIPOLYGON (((1162356 654773.5, 1162224 654672.7, 1162194 654802.…

plot(coastal_airzones)
```

![](https://i.imgur.com/e8EnGjM.png)

**Comment by stephhazlitt** [comment]
I feel like it might be some of the processing or caching by `bcmaps`? The raw data file works fine with `bcdata` (which might be a good workaround for you in the interim @jeromerobles).

The resulting values in the `geometry` column in the `bcmaps` tibble has `POLYGON` or `MULTIPOLYGON` which is not in the `bcdata` tibble:

``` r
airzones_bcmaps <- bcmaps::airzones()
#> airzones was updated on NULL
coastal_airzones_bcmaps <- airzones_bcmaps[airzones_bcmaps$Airzone %in% c("Coastal", "Georgia Strait"), ]
coastal_airzones_bcmaps
#> Simple feature collection with 2 features and 1 field
#> Geometry type: GEOMETRY
#> Dimension:     XY
#> Bounding box:  xmin: 962121.4 ymin: 578792.6 xmax: 1264425 ymax: 835719.9
#> Projected CRS: NAD83 / BC Albers
#> # A tibble: 2 × 2
#>   Airzone                                                               geometry
#>   <chr>                                                           <GEOMETRY [m]>
#> 1 Coastal        MULTIPOLYGON (((1162356 654773.5, 1162224 654672.7, 1162194 65…
#> 2 Georgia Strait POLYGON ((1264304 579248.2, 1264425 579131.4, 1264360 578846.4…
plot(coastal_airzones_bcmaps)
```

![](https://i.imgur.com/2kb5jza.png)

``` r

airzones_bcdata <- bcdata::bcdc_get_data(record = 'e8eeefc4-2826-47bc-8430-85703d328516', 
                                         resource = '4cea4b22-36a3-4ea7-9346-7e872e747076')
#> Reading the data using the read_sf function from the sf package.
coastal_airzones_bcdata <- airzones_bcdata[airzones_bcdata$Airzone %in% c("Coastal", "Georgia Strait"), ]
coastal_airzones_bcdata
#> Simple feature collection with 2 features and 1 field
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 485170.8 ymin: 360742.5 xmax: 1264674 ymax: 1260894
#> Projected CRS: Albers
#> # A tibble: 2 × 2
#>   Airzone                                                               geometry
#>   <chr>                                                       <MULTIPOLYGON [m]>
#> 1 Coastal        (((1162224 654672.7, 1162194 654802.2, 1162271 654852.9, 11623…
#> 2 Georgia Strait (((1263164 579153.2, 1264304 579248.2, 1264425 579131.4, 12643…
plot(coastal_airzones_bcdata)
```

![](https://i.imgur.com/wh71ppL.png)

<sup>Created on 2023-07-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by boshek** [comment]
Ah yes you said as much before. Sorry for not noticing. So the behaviour you see is introduced here:

https://github.com/bcgov/bcmaps/blob/d09b4a049903dbf487539a6f0893596cea64aaf9/R/get_data.R#L147-L148

**Comment by ateucher** [comment]
It looks like it might be all the things!

The resource you were testing against using bcdata is the [shapefile resource](https://catalogue.data.gov.bc.ca/dataset/british-columbia-air-zones/resource/4cea4b22-36a3-4ea7-9346-7e872e747076), whereas bcmaps uses the [geojson resource](https://catalogue.data.gov.bc.ca/dataset/british-columbia-air-zones/resource/c495d082-b586-4df0-9e06-bd6b66a8acd9)... and apparently they are slightly different - The projections are different (The shapefile is in a global (not BC) Albers projection (EPSG: 9001), while the geojson is in WGS84 (lat long) - this does make sense as that is the standard for geojson, though the shapefile should probably be EPSG:3005 (BC Albers). @boshek is right that it is the `st_make_valid()` line that is causing the issue, but it seems we can resolve it by switching the order of `st_make_valid()` and `st_transform()` here: 

https://github.com/bcgov/bcmaps/blob/d09b4a049903dbf487539a6f0893596cea64aaf9/R/get_data.R#L145C1-L146. 

``` r
library(sf)
#> Linking to GEOS 3.11.0, GDAL 3.5.3, PROJ 9.1.0; sf_use_s2() is TRUE
library(bcdata)
#> 
#> Attaching package: 'bcdata'
#> The following object is masked from 'package:stats':
#> 
#>     filter

## The shapefile resource
az_shp <- bcdc_get_data(record = 'e8eeefc4-2826-47bc-8430-85703d328516',
                    resource = '4cea4b22-36a3-4ea7-9346-7e872e747076')
#> Reading the data using the read_sf function from the sf package.

st_crs(az_shp)
#> Coordinate Reference System:
#>   User input: Albers 
#>   wkt:
#> PROJCRS["Albers",
#>     BASEGEOGCRS["GCS_GRS 1980(IUGG, 1980)",
#>         DATUM["D_unknown",
#>             ELLIPSOID["GRS80",6378137,298.257222101,
#>                 LENGTHUNIT["metre",1,
#>                     ID["EPSG",9001]]]],
#>         PRIMEM["Greenwich",0,
#>             ANGLEUNIT["Degree",0.0174532925199433]]],
#>     CONVERSION["unnamed",
#>         METHOD["Albers Equal Area",
#>             ID["EPSG",9822]],
#>         PARAMETER["Latitude of false origin",45,
#>             ANGLEUNIT["Degree",0.0174532925199433],
#>             ID["EPSG",8821]],
#>         PARAMETER["Longitude of false origin",-126,
#>             ANGLEUNIT["Degree",0.0174532925199433],
#>             ID["EPSG",8822]],
#>         PARAMETER["Latitude of 1st standard parallel",50,
#>             ANGLEUNIT["Degree",0.0174532925199433],
#>             ID["EPSG",8823]],
#>         PARAMETER["Latitude of 2nd standard parallel",58.5,
#>             ANGLEUNIT["Degree",0.0174532925199433],
#>             ID["EPSG",8824]],
#>         PARAMETER["Easting at false origin",1000000,
#>             LENGTHUNIT["metre",1],
#>             ID["EPSG",8826]],
#>         PARAMETER["Northing at false origin",0,
#>             LENGTHUNIT["metre",1],
#>             ID["EPSG",8827]]],
#>     CS[Cartesian,2],
#>         AXIS["(E)",east,
#>             ORDER[1],
#>             LENGTHUNIT["metre",1,
#>                 ID["EPSG",9001]]],
#>         AXIS["(N)",north,
#>             ORDER[2],
#>             LENGTHUNIT["metre",1,
#>                 ID["EPSG",9001]]]]
st_is_valid(az_shp)
#> [1]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE

## The resource (geojson) that bcmaps uses in airzones()
az_geojson <- bcdc_get_data(record = 'e8eeefc4-2826-47bc-8430-85703d328516',
                    resource = 'c495d082-b586-4df0-9e06-bd6b66a8acd9')
#> Reading the data using the read_sf function from the sf package.

st_crs(az_geojson)
#> Coordinate Reference System:
#>   User input: WGS 84 
#>   wkt:
#> GEOGCRS["WGS 84",
#>     DATUM["World Geodetic System 1984",
#>         ELLIPSOID["WGS 84",6378137,298.257223563,
#>             LENGTHUNIT["metre",1]]],
#>     PRIMEM["Greenwich",0,
#>         ANGLEUNIT["degree",0.0174532925199433]],
#>     CS[ellipsoidal,2],
#>         AXIS["geodetic latitude (Lat)",north,
#>             ORDER[1],
#>             ANGLEUNIT["degree",0.0174532925199433]],
#>         AXIS["geodetic longitude (Lon)",east,
#>             ORDER[2],
#>             ANGLEUNIT["degree",0.0174532925199433]],
#>     ID["EPSG",4326]]
st_is_valid(az_geojson)
#> [1]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE

## Transform first, then make valid:
plot(
  st_make_valid(st_transform(az_shp, 3005)),
  main = "shp: transform, then make valid"
)
```

![](https://i.imgur.com/a4Qjg08.png)

``` r
plot(st_make_valid(
  st_transform(az_geojson, 3005)
), main = "geojson: transform, then make valid")
```

![](https://i.imgur.com/VY5mRKw.png)

``` r

## Make valid first, then transform
plot(st_transform(
  st_make_valid(az_shp),
  3005
), main = "shp: make valid, then transform")
```

![](https://i.imgur.com/R3JJSWs.png)

``` r
plot(st_transform(
  st_make_valid(az_geojson),
  3005
), main = "geojson: make valid, then transform")
```

![](https://i.imgur.com/BKagM5z.png)

``` r

st_transform(st_make_valid(az_shp), 3005)
#> Simple feature collection with 7 features and 1 field
#> Geometry type: GEOMETRY
#> Dimension:     XY
#> Bounding box:  xmin: 272458 ymin: 360742.5 xmax: 1872244 ymax: 1735332
#> Projected CRS: NAD83 / BC Albers
#> # A tibble: 7 × 2
#>   Airzone                                                               geometry
#> * <chr>                                                           <GEOMETRY [m]>
#> 1 Northeast           POLYGON ((1332343 1684516, 1388377 1033256, 1377903 10285…
#> 2 Northwest           POLYGON ((272458 1735332, 365988.2 1719589, 515080.9 1697…
#> 3 Southern Interior   POLYGON ((1565810 831252.7, 1573864 823888.6, 1576626 828…
#> 4 Lower Fraser Valley POLYGON ((1326899 580398.9, 1334263 578097.6, 1334493 569…
#> 5 Central Interior    POLYGON ((962140 835637.9, 952596.4 831566, 950347.4 8339…
#> 6 Coastal             MULTIPOLYGON (((1162194 654802.2, 1162271 654852.9, 11623…
#> 7 Georgia Strait      MULTIPOLYGON (((1252569 578270.3, 1250496 578097.6, 12495…
st_transform(st_make_valid(az_geojson), 3005)
#> Simple feature collection with 7 features and 1 field
#> Geometry type: MULTIPOLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 272458 ymin: 360742.5 xmax: 1872244 ymax: 1735332
#> Projected CRS: NAD83 / BC Albers
#> # A tibble: 7 × 2
#>   Airzone                                                               geometry
#> * <chr>                                                       <MULTIPOLYGON [m]>
#> 1 Northeast           (((1196093 1673266, 1053593 1669516, 962342.7 1669516, 89…
#> 2 Northwest           (((289126.8 1722367, 292830.9 1723294, 291904.9 1709403, …
#> 3 Southern Interior   (((1554878 833784.1, 1552347 839077.1, 1559826 850928.6, …
#> 4 Lower Fraser Valley (((1326761 579850.8, 1325240 580298.3, 1320637 571553.5, …
#> 5 Central Interior    (((968603.7 825480.6, 976012.1 809208.7, 981700.6 808811.…
#> 6 Coastal             (((1162356 654773.5, 1162271 654852.9, 1162194 654802.2, …
#> 7 Georgia Strait      (((1263105 578917.6, 1263259 578792.6, 1264360 578846.4, …
```

<sup>Created on 2023-07-31 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

So I think on the backend there could be some work done to post topologically valid geometries in the appropriate projections in the various files.  And in bcmaps we could test switching the order of those two lines in `get_catalogue_data()` to make sure it would work across all data sets?

My hypothesis (that I'm likely not going to test any time soon) is that this change is due to newer versions of `{sf}` using the s2 geometry engine instead of GEOS for geographic operations, which made `st_make_valid()` and (more likely) `st_transform()` behave differently than it did in the past.

**Comment by stephhazlitt** [comment]
So I am clear on DOD re: 

> test switching the order of those two lines in get_catalogue_data() to make sure it would work across all data sets

This means we switch the code, clear our cache and then pull _every_ shortcut function and see if the resulting map looks correct?

**Comment by ateucher** [comment]
Yep, basically. There's probably some more efficient way to do it, maybe in a qmd and a loop similar to the [tests](https://github.com/bcgov/bcmaps/blob/d09b4a049903dbf487539a6f0893596cea64aaf9/tests/testthat/test-data_functions.R#L4-L24)?

**Comment by stephhazlitt** [comment]
I'll open a ticket with the BC Data Catalogue re: topologically valid geometries in the appropriate projections for this file (and presumably others).

**Comment by ateucher** [comment]
Here's a comparison of all of the maps using shortcuts with the order of the two operations switched:

``` r
library(bcmaps)
#> Loading required package: sf
#> Linking to GEOS 3.11.0, GDAL 3.5.3, PROJ 9.1.0; sf_use_s2() is TRUE
#> Support for Spatial objects (`sp`) was deprecated in {bcmaps} v1.2.0, and will be removed altogether in the Summer 2023. Please use `sf` objects with {bcmaps}.
library(sf)
avail <- available_layers()
fn_names <- avail$layer_name[
  !avail$local &
    !grepl("cded_", avail$layer_name) &
    avail$using_shortcuts
]

fn_names <- setdiff(fn_names, c("bec", "tsa"))
par(mfrow = c(1,2))

for (i in seq_along(fn_names)) {
  delete_cache()
  cat("\n", fn_names[i])
  
  layer <- do.call(fn_names[i], list(ask = FALSE, force = TRUE))
  plot(st_geometry(layer), main = "st_transform then st_make_valid")
  
  delete_cache()
  
  withr::with_envvar(c("MAKEVALID_BEFORE_TRANSFORM" = "true"), {
    layer2 <- do.call(fn_names[i], list(ask = FALSE, force = TRUE))
    plot(st_geometry(layer2), main = "st_make_valid then st_transform")
  })
}
#> 
#>  airzones
#> Reading the data using the read_sf function from the sf package.
#> original order
#> Reading the data using the read_sf function from the sf package.
#> trying the reverse thing
#> 
#>  bc_cities
#> original order
```

![](https://i.imgur.com/DbzPYyA.png)

    #> trying the reverse thing
    #> 
    #>  census_dissemination_area
    #> original order

![](https://i.imgur.com/XtMQUkf.png)

    #> trying the reverse thing
    #> 
    #>  census_division
    #> original order

![](https://i.imgur.com/yTjnA5G.png)

    #> trying the reverse thing
    #> 
    #>  census_economic
    #> original order

![](https://i.imgur.com/RaRAcRQ.png)

    #> trying the reverse thing
    #> 
    #>  census_metropolitan_area
    #> original order

![](https://i.imgur.com/4c2qpXY.png)

    #> trying the reverse thing
    #> 
    #>  census_subdivision
    #> original order

![](https://i.imgur.com/ftFDMjd.png)

    #> trying the reverse thing
    #> 
    #>  census_tract
    #> original order

![](https://i.imgur.com/hIeGjzs.png)

    #> trying the reverse thing
    #> 
    #>  ecoprovinces
    #> original order

![](https://i.imgur.com/LaAXvSy.png)

    #> trying the reverse thing
    #> 
    #>  ecoregions
    #> original order

![](https://i.imgur.com/LbbwDdM.png)

    #> trying the reverse thing
    #> 
    #>  ecosections
    #> original order

![](https://i.imgur.com/EGsWxv8.png)

    #> trying the reverse thing
    #> 
    #>  gw_aquifers
    #> original order

![](https://i.imgur.com/gSRA2pe.png)

    #> trying the reverse thing
    #> 
    #>  health_chsa
    #> original order

![](https://i.imgur.com/ifQFm0R.png)

    #> trying the reverse thing
    #> 
    #>  health_ha
    #> original order

![](https://i.imgur.com/uJ5ULk2.png)

    #> trying the reverse thing
    #> 
    #>  health_hsda
    #> original order

![](https://i.imgur.com/VjaVg41.png)

    #> trying the reverse thing
    #> 
    #>  health_lha
    #> original order

![](https://i.imgur.com/rprXQIR.png)

    #> trying the reverse thing
    #> 
    #>  hydrozones
    #> original order

![](https://i.imgur.com/IGTKQ9P.png)

    #> trying the reverse thing
    #> 
    #>  municipalities
    #> original order

![](https://i.imgur.com/YKGLp6g.png)

    #> trying the reverse thing
    #> 
    #>  nr_areas
    #> You are accessing a simplified view of the data - see the catalogue record for details.
    #> original order

![](https://i.imgur.com/322HwLo.png)

    #> You are accessing a simplified view of the data - see the catalogue record for details.
    #> trying the reverse thing
    #> 
    #>  nr_districts
    #> You are accessing a simplified view of the data - see the catalogue record for details.
    #> original order

![](https://i.imgur.com/W2XIdJy.png)

    #> You are accessing a simplified view of the data - see the catalogue record for details.
    #> trying the reverse thing
    #> 
    #>  nr_regions
    #> You are accessing a simplified view of the data - see the catalogue record for details.
    #> original order

![](https://i.imgur.com/3LnbWH2.png)

    #> You are accessing a simplified view of the data - see the catalogue record for details.
    #> trying the reverse thing
    #> 
    #>  regional_districts
    #> original order

![](https://i.imgur.com/ui0ghNn.png)

    #> trying the reverse thing
    #> 
    #>  water_districts
    #> original order

![](https://i.imgur.com/WuvajXp.png)

    #> trying the reverse thing
    #> 
    #>  water_precincts
    #> original order

![](https://i.imgur.com/ZTTmSJ7.png)

    #> trying the reverse thing
    #> 
    #>  wsc_drainages
    #> original order

![](https://i.imgur.com/Q9KWiuO.png)

    #> trying the reverse thing

![](https://i.imgur.com/jjS4Qaq.png)

<sup>Created on 2023-08-11 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by stephhazlitt** [comment]
LGTM, thanks for doing this @ateucher. I will work with the catalogue to get the source airzone map sorted as well.

**Comment by boshek** [comment]
It _would_ be nice to know exactly why. Having the order (which seemed arbitrary) change exactly which geometries are returns isn't ideal... 

Am I reading this right that the only one this affected was the `airzones`?

**Comment by jeromerobles** [comment]
Thank you all for looking into this. Let me know if you need to get the map creation history, i.e., whether it was generated using QGIS, or ArcGIS, and any types of processing that were applied in its creation. I know in certain air-related maps, boundaries are redefined and new map iterations are made following consultations.

**Comment by stephhazlitt** [comment]
FYI, looks like @jeromerobles and @ateucher are listed as the data providers for this layer in the BCDC. So @jeromerobles if you want to fix this issue at the source (the raw data available in the BCDC) then I guess it is up to you or your team to evaluate and re-submit a clean layer.
