### ISSUE TITLE
Hydrometric station watershed boundaries?

### ISSUE THREAD

**Issue by markjohnsonubc** [bcgov/bcmaps#14]
Would be great if you could also pull in this dataset
https://catalogue.data.gov.bc.ca/dataset/hydrology-hydrometric-watershed-boundaries

**Comment by ateucher** [comment]
This would be a great addition, thanks @markjohnsonubc for the idea. We'll put it at the top of the list, but it may take a couple of weeks before we can get to to it. 

In the meantime, I'd be very happy to get a pull request! If you feel like taking it on, you can follow one of the examples in the `data-raw` folder (ecoregions is a good one).

**Comment by markjohnsonubc** [comment]
OK - I think this is all OK now. I've done the pull request with the updates.
cheers - Mark

**Comment by ateucher** [comment]
Closed by #15
