### ISSUE TITLE
cded_raster deprication lifecycle message doesn't print properly

### ISSUE THREAD

**Issue by bevingtona** [bcgov/bcmaps#140]
Looks like the deprication message for cded_raster() has a glitch and doen't print the full message. not sure why? The functions seems well written in https://github.com/bcgov/bcmaps/blob/main/R/cded.R (line 174).. 

``` r
bcmaps::cded_raster(aoi = bcmaps::bc_cities()[1,])
#> Error in parse(text = x, keep.source = FALSE): <text>:1:14: unexpected symbol
#> 1: cded_stars() or
#>                  ^
```

<sup>Created on 2023-11-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by stephhazlitt** [comment]
Interesting. It is the [`with = "cded_stars() or cded_terra()"`]( https://github.com/bcgov/bcmaps/blob/main/R/cded.R#L174) line, {lifecycle} does not like the multiple functions in that argument (it bonks with the space or any string with more than one `()`). The design is replace one function with one function, so my guess the regex in {lifecycle} does not like this create use.

We could remove the `with` argument and add the fxns to `details`? e.g.,

`details = "bcmaps has begun dropping support for raster objects. Please consider switching to terra [cded_terra()] or stars [cded_stars()]."`

**Comment by bevingtona** [comment]
Yeah that sounds great, thanks @stephhazlitt :) Not mission critical obviously, just a tiny bug

**Comment by stephhazlitt** [comment]
@bevingtona do you want to make a PR with this small tweak?

**Comment by stephhazlitt** [comment]
@bevingtona Thanks for putting up the PR 🙌 Let's closed this after the review+merge ⛙.
