### ISSUE TITLE
function request: transform bc albers to long lat

### ISSUE THREAD

**Issue by MichaelFolkes** [bcgov/bcmaps#145]
I've had a read of the vignette and looked at list of available functions, but cannot see a way of transforming from bc albers to long lat. Am I missing it?

**Comment by boshek** [comment]
Hey Michael. I believe that this would be function that would be beyond the scope of bcmaps. Luckily it _is_ in the scope of the sf package. I think that `sf::st_coordinates` is probably what you are looking for? You can read more here: https://r-spatial.github.io/sf/reference/st_coordinates.html

**Comment by MichaelFolkes** [comment]
thanks!
