### ISSUE TITLE
Request: Vignette example of choropleth map

### ISSUE THREAD

**Issue by pssguy** [bcgov/bcmaps#16]
and/or a link to a worked example

Thanks

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation](https://trello.com/c/hMnhbSgF/2-documentation)

**Comment by boshek** [comment]
Is this not addressed sufficiently by [this figure](https://github.com/bcgov/bcmaps/blob/new-frontend/tools/readme/unnamed-chunk-6-1.png) in the [README](https://github.com/bcgov/bcmaps/tree/new-frontend#usage).?

**Comment by boshek** [comment]
Sufficient example present here: https://github.com/bcgov/bcmaps/blob/master/README.md#usage
