### ISSUE TITLE
For large files that are downloadable, download via fn instead of store them

### ISSUE THREAD

**Issue by ateucher** [bcgov/bcmaps#2]
For example, `regional_districts_analysis` could be a function that downloads the data and builds the object. Would be a bit slow, and require internet access. Tradeoff on speed vs file size

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enhancements](https://trello.com/c/SwdthTQG/4-enhancements)

**Comment by boshek** [comment]
This might be useful for us: https://journal.r-project.org/archive/2017/RJ-2017-026/index.html

**Comment by ateucher** [comment]
Thanks @boshek I saw that too. Would require setting up a drat repo - which I don't think is hard, but another thing to maintain... Will have to mull the benefits over just having a GH repo with releases and the files attached to the releases...

**Comment by boshek** [comment]
Closed via https://github.com/bcgov/bcmaps/pull/25
