### ISSUE TITLE
Move from sp to sf package for generating spatial data objects for R

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/bcmaps#21]

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Enhancements](https://trello.com/c/SwdthTQG/4-enhancements)

**Comment by boshek** [comment]
Unless I am missing something, which is quite possible, moving this from sp to sf should be quite easily. The problem I see here is that this change will break code. Folks that use this package and depend on the `sp` data structure might not love the change. Just a couple questions/ideas to consider:

- Do you have any idea of the package user base? How many people use this?
- Once the change has been made to sf, a library load message warning users that data has been converted to `sf` might be useful and...
- Keep all `sp` data in a legacy package for a while (`bcmaps_sp`?) and in the package load message, direct users to that repo if they don't want to convert their code. 
- Might be prudent to wait until `geom_sf` becomes part of the `ggplot2` CRAN package as has been mentioned elsewhere.

**Comment by stephhazlitt** [comment]
Agreed & great suggestions @boshek. In a perfect world we would also complete this [enhancement](https://github.com/bcgov/bcmaps/issues/2) at the same time.

**Comment by boshek** [comment]
Closed via https://github.com/bcgov/bcmaps/pull/25
