### ISSUE TITLE
Add Water Survey of Canada sub-sub drainage areas

### ISSUE THREAD

**Issue by boshek** [bcgov/bcmaps#22]
Link to layer on DataBC: https://catalogue.data.gov.bc.ca/dataset/water-survey-of-canada-sub-sub-drainage-areas

A slightly less easily nameable dataset - possibly `wsc_drainages`

**Comment by stephhazlitt** [comment]
Are these nested in or related to [bcmaps::watersheds](http://catalogue.data.gov.bc.ca/dataset/hydrology-hydrometric-watershed-boundaries)?

**Comment by boshek** [comment]
I'm not totally sure how they are related. In fact I am a little confused by the `watersheds` layer. Plotting it along the `wsc_drainages` layer is a bit confusing:

![image](https://user-images.githubusercontent.com/18472598/27753118-4548b0dc-5d99-11e7-9fe9-27c99df486c2.png)

Whatever the case, the `wsc_drainages` layer has watersheds named in line with hydrometric station naming. For example, the station 08KH001 is a hydrometric station that drains into the Pacific (08) nested in the Upper Fraser (08K) nested in the Quesnel watershed (08KH). The `wsc_drainages` shape file use all these naming conventions with the appropriate spatial data.

**Comment by stephhazlitt** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bcmaps::In Progress](https://trello.com/c/cnPRtTSh/11-bcmapsin-progress)
