### ISSUE TITLE
Support for Health Boundaries? 

### ISSUE THREAD

**Issue by andkov** [bcgov/bcmaps#24]
Hello,
   was very excited to see this repo. I read through the list, but didn't find support for boundaries for health service system units (please see http://www2.gov.bc.ca/gov/content/data/geographic-data-services/land-use/administrative-boundaries/health-boundaries). 
   I am a postdoctoral researcher, starting to look at surveillance and monitoring at provincial level and searching for the maps the correspond to these boundaries. I am specifically looking for something that can work in R and ggplot universe.

**Comment by stephhazlitt** [comment]
Hi @andkov. See the [B.C. Data Catalogue](https://catalogue.data.gov.bc.ca/dataset) for source layers for provincial data. I found a few [hits with "health + boundaries"](https://catalogue.data.gov.bc.ca/dataset?q=health+boundaries). A source layer needs to be available under the [Open Government Licence&ndash;British Columbia](http://www2.gov.bc.ca/gov/content/data/open-data/open-government-license-bc) to be included in `bcmaps`. It looks like these layers are [Access Only](http://www2.gov.bc.ca/gov/content/home/copyright) at this time&mdash;you can [contact DataBC](https://forms.gov.bc.ca/databc-contact-us/) to ask about the possibility of these layers being made open.

**Comment by andkov** [comment]
@stephhazlitt , thank you for the links. It appears that the files I need can be found there:
- LHA - [Local Health Area Boundaries](https://catalogue.data.gov.bc.ca/dataset/local-health-area-boundaries-generalized)  
- HSDA - [Health Service Delivery Area Boundaries](https://catalogue.data.gov.bc.ca/dataset/health-service-delivery-area-boundaries)  
- HA - [Health Authority Boundaries](https://catalogue.data.gov.bc.ca/dataset/health-authority-boundaries)   

I will look into requesting DataBC to opening these layers, thank you for the suggestion.
