### ISSUE TITLE
Outside of BC layer

### ISSUE THREAD

**Issue by boshek** [bcgov/bcmaps#36]
To flesh out some plotting capabilities of `bcmaps` I wonder if it might be useful to have an "external to bc" layer. For example, we typically may plot the province using either `bc_bound()` or `bc_bound_hres()` like this:
![image](https://user-images.githubusercontent.com/18472598/37839881-dcc1dd16-2e78-11e8-82fa-8cbca63d06b8.png)

If we had an `outside_bc_border()` layer like this:
![image](https://user-images.githubusercontent.com/18472598/37840185-a0886aee-2e79-11e8-8603-12fda0a1d728.png)

We could combine them in instances where don't want BC floating on its own in space:
![image](https://user-images.githubusercontent.com/18472598/37840260-cf9c56c4-2e79-11e8-97b9-e764bb4c316c.png)

Is this something we'd want in `bcmaps`? Or is it better to leave up to a user to create?

Here is how I created the layer. I am still struggling with how to create a perfectly square box on a projected surface. Also I am currently sourcing the data from the `raster` package but this may not be a tenable long term solution to store over in `bcmaps.rdata`:

```
library(here)
library(raster)
library(bcmaps)
library(sf)
library(dplyr)
library(ggplot2) #dev



# Load spatial layers -----------------------------------------------------

data_path <- here("data")

canada_border <- raster::getData('GADM', country="CAN", path = data_path, level=1) 

usa_border <- raster::getData('GADM', country="USA", path = data_path, level=1) 

## Square box on projected surface
coords = list(matrix(c(-142, 61,
                       -138, 47,
                       -114, 47,
                       -110, 61,
                       -142, 61),
                ncol = 2,
                byrow = TRUE))

outside_bc_box <- st_polygon(coords) %>%
  st_sfc(crs = 4326) %>%
  transform_bc_albers() 


# Spatial manipulations ---------------------------------------------------

canada_border <- st_as_sf(canada_border) %>%
  transform_bc_albers()

usa_border <- st_as_sf(usa_border) %>%
  transform_bc_albers()


outside_bc_border <- rbind(canada_border, usa_border) %>%
  st_intersection(outside_bc_box) %>%
  filter(!NAME_1 == "British Columbia")


# Plots -------------------------------------------------------------------

ggplot() +
  geom_sf(data = bc_bound_hres(), fill = "purple") +
  theme_void()

ggplot() +
  geom_sf(data = outside_bc_border) +
  theme_void()

ggplot() +
  geom_sf(data = bc_bound_hres(), fill = "purple") +
  geom_sf(data = outside_bc_border) +
  theme_void()
```

**Comment by ateucher** [comment]
I like it! After our discussion in person, I think the idea of adding a chunk of the pacific ocean to fill out the box is a good one. Also, I think maybe don't do the `st_intersection()` to remove BC?

**Comment by ateucher** [comment]
I wonder too if it's going to be mainly (only) for plotting purposes we could keep the size down by running it through `ms_simplify()`?

**Comment by boshek** [comment]
Great suggestions. I'm going to make a task list here to check off before merging this into the master branch while this is fresh as this could take awhile as some of these things are beyond our control:

- [ ] Find layers with an open license for both USA and Canada
- [ ] Use ms_simplify to reduce size and test that it doesn't impact plotting
- [ ] Wait for a CRAN version of `ggplot2` that includes `geom_sf()`
- [ ] Add chunk of Pacific Ocean as an attribute in the layer
- [ ] Keep BC in the layer

Also @ateucher proposed the name `bc_neighbours()`
