### ISSUE TITLE
Use bcdata as backend for relevant layers

### ISSUE THREAD

**Issue by stephhazlitt** [bcgov/bcmaps#47]
Is it worth thinking about the future use cases of `bcmaps` versus `bcdata`? For map layers available with `bcdata` should users use that package to ensure always grabbing the most up-to-date versions (without any tinkering with `bcmapsdata`)? Perhaps `bcmaps` becomes the home for open layers from the 🇨🇦 open data catalogue, maps not available via WMS/WFS, and a set of helper functions (e.g. `bc_neighbours()`)? Thoughts @ateucher @boshek?

**Comment by boshek** [comment]
I think this is a good idea to at least evaluate where we might have duplication. I wonder if to avoid breaking any old code, we could simply use bcdata on the backend for any layers that we didn't want to include? Here is a list that we could use to ID those that aren't likely to change.  We could check those that 

- [ ]           airzones                                    British Columbia Air Zones
- [ ]           bc_bound                                                   BC Boundary
- [ ]      bc_bound_hres                                 BC Boundary - High Resolution
- [ ]          bc_cities BC Major Cities Points 1:2,000,000 (Digital Baseline Mapping)
- [ ]      bc_neighbours                    British Columbia and neighbouring features
- [ ]       ecoprovinces                                 British Columbia Ecoprovinces
- [ ]         ecoregions                                   British Columbia Ecoregions
- [ ]        ecosections                                  British Columbia Ecosections
- [ ]        gw_aquifers            British Columbia's developed ground water aquifers
- [ ]         hydrozones                Hydrologic Zone Boundaries of British Columbia
- [ ]     municipalities                               British Columbia Municipalities
- [ ]           nr_areas                  British Columbia Natural Resource (NR) Areas
- [ ]       nr_districts              British Columbia Natural Resource (NR) Districts
- [ ]         nr_regions                British Columbia Natural Resource (NR) Regions
- [ ] regional_districts                           British Columbia Regional Districts
- [ ]    water_districts                 British Columbia's Water Management Districts
- [ ]    water_precincts                 British Columbia's Water Management Precincts
- [ ]   watercourses_15M                  British Columbia watercourses at 1:15M scale
- [ ]    watercourses_5M                   British Columbia watercourses at 1:5M scale
- [ ]      wsc_drainages                 Water Survey of Canada Sub-Sub-Drainage Areas
- [ ]                bec                                      British Columbia BEC Map
- [ ]                tsa                         B.C. Timber Supply Areas & TSA Block

**Comment by stephhazlitt** [comment]
I totally agree we do not want to break code. I am also thinking of how we might help/promote users to update code using `bcdata` when appropriate. Was thinking a deprecated `WARNING` with some bread crumbs to lead ppl to `bcdata` might be one approach for those layers where `bcdata` is the obvious new kid on the block?

**Comment by boshek** [comment]
This seems like a great approach. Once bcdata is on CRAN, this seems viable.

**Comment by stephhazlitt** [comment]
Some thoughts on how to implement this if [caching in `bcdata`](https://github.com/bcgov/bcdata/issues/5) is not available, _and_ considering the challenge of no resource date-stamp: 

• use `bcdata` as the back-end for the catalogue layers and implement caching of downloaded layer in `bcmaps`
• rather than checking for new versions of downloaded data, provide the user with date of initial download and length of time that has passed _Hey - it has been awhile since you pulled this data layer, maybe consider refreshing?_
• for `watercourses*()` and `bc_bound_hres()` layers, house them _in_ the `bcmaps()` package (assuming size is reasonable?) and set-up an issue open action for letting package maintainers know that new versions have been released in the [The Canadian Open Data Portal](http://open.canada.ca/data/en/dataset/f77c2027-ed4a-5f6e-9395-067af3e9fc1e). MVP of this [here](https://github.com/bcgov/hydrometric_stations/blob/master/.github/workflows/hydatupdate.yaml).

**Comment by boshek** [comment]
What I have just realized is that we can very readily leverage the downloading capabilities build by @ateucher here: https://github.com/bcgov/bcmaps/blob/master/R/download_data.R

**Comment by ateucher** [comment]
I kind of forgot about that! Maybe doing the caching in `bcmaps` is the answer, as caching in `bcdata` is more complicated due to the querying...

**Comment by boshek** [comment]
WIP #60
