### ISSUE TITLE
Issues with transform_bc_albers on certain files

### ISSUE THREAD

**Issue by joburgar** [bcgov/bcmaps#50]
Hello,

I'm trying to reproject a sf object (IAF_tnsct_sf - originally in epsg 4326) into Albers but the geometry seems off by 1000 and the x coords are positive when I do so. Any suggestions on how to fix this?

Thanks,
Joanna

________________________________________________________________________
OGR data source with driver: ESRI Shapefile 
Source: "/Users/joburgar/Google Drive/20190629_iaf_jburgar/gis_1701scbat_iaf/03_t3_bioacoustics", layer: "abm_iaf_transect"
with 8 features
It has 16 fields
Integer64 fields read as strings:  OID_ SymbolID 
Warning message:
In readOGR(dsn = "./03_t3_bioacoustics", layer = "abm_iaf_transect") :
  Z-dimension discarded
> class(IAF_tnsct) # sp class
[1] "SpatialLinesDataFrame"
attr(,"package")
[1] "sp"
> # convert to sf object
> IAF_tnsct_sf <- st_as_sf(IAF_tnsct)
> class(IAF_tnsct_sf) # sf class
[1] "sf"         "data.frame"

> st_crs(IAF_tnsct_sf) # EPSG: 4326
Coordinate Reference System:
  EPSG: 4326 
  proj4string: "+proj=longlat +datum=WGS84 +no_defs"
> extent(IAF_tnsct_sf)
class      : Extent 
xmin       : -123.0646 
xmax       : -121.3979 
ymin       : 49.00224 
ymax       : 49.34879 

> IAF_tnsct_sf_alb <- transform_bc_albers(IAF_tnsct_sf)
> st_crs(IAF_tnsct_sf_alb) # EPSG: 3005
Coordinate Reference System:
  EPSG: 3005 
  proj4string: "+proj=aea +lat_1=50 +lat_2=58.5 +lat_0=45 +lon_0=-126 +x_0=1000000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs"
> extent(IAF_tnsct_sf_alb)
class      : Extent 
xmin       : 1214444 
xmax       : 1336605 
ymin       : 448779 
ymax       : 487261.3 

[Archive.zip](https://github.com/bcgov/bcmaps/files/3449332/Archive.zip)

**Comment by boshek** [comment]
Hi @joburgar,

I extracted your .zip file to a data director locally. That is what is being referenced here. I am trying to under the issue. I have plotted the transformation and it looks good to me. Note I've just used `sf` to load in the data right away. See below and let's see if we can figure out what your issue is:

``` r
library(sf)
library(bcmaps)
library(ggplot2)
library(dplyr)

## Add a part of BC for context
bc <- nr_regions() %>%
  filter(REGION_NAME == "South Coast Natural Resource Region") %>% 
  st_transform(4326)

## Just read in with sf?
IAF_tnsct_sf <- read_sf("data/abm_iaf_transect.shp")

## Plot with 4326 projection - looks good
ggplot() +
  geom_sf(data = IAF_tnsct_sf, colour = "pink") +
  geom_sf(data = bc, fill = NA)

## Transform to BC Albers
to_albers <- IAF_tnsct_sf %>% 
  transform_bc_albers() 

## Leave BC part in BC Albers
bc <- nr_regions() %>%
  filter(REGION_NAME == "South Coast Natural Resource Region")

## Plot - still looking good.
ggplot() +
  geom_sf(data = to_albers, colour = "pink") +
  geom_sf(data = bc, fill = NA)
```

**Comment by joburgar** [comment]
Thanks for checking into this - much appreciated! It plots perfectly fine with the bc maps data and the extent makes more sense.
