### ISSUE TITLE
Old version of NRD

### ISSUE THREAD

**Issue by bevingtona** [bcgov/bcmaps#54]
Just noticed that the Natural Resource Districts layer (called with the bcmaps function `bcmaps::nr_districts()`) is an old version of the districts. The data catalogue has a newer version (found here: https://catalogue.data.gov.bc.ca/dataset/natural-resource-nr-district). 

The only difference is that the Vanderhoof and Fort St. James districs have been merged into a single district named Stuart Nechako. 

Great package as always - my go to for quick access to pretty maps!

![image](https://user-images.githubusercontent.com/9651129/75049030-58c2df00-547e-11ea-9c94-83538468e6ea.png)

**Comment by boshek** [comment]
Thanks @bevingtona 

Do you know if any of the other `nr_*` layers are impacted?

**Comment by stephhazlitt** [comment]
I think this issue speaks to the proposal to revamp `bcmaps` to either (i) use `bcdata` under the hood to access these layers programmatically (as opposed to via a stored copy in `bcmapsdata`) or (ii) deprecate/defunct many of the `bcmaps` functions with a note to use `bcdata` and morph `bcmaps` into a bc mapping utilities package.

**Comment by stephhazlitt** [comment]
> Do you know if any of the other nr_* layers are impacted?

It is likely that many/some of the layers in `bcmapsdata` have been superseded by newer versions. Perhaps a quick fix is to morpth this issue into update the files `raw-data` of `bcmapsdata`?

**Comment by boshek** [comment]
@bevingtona I've updated the bcmapsdata package. Try reinstalling using this:

```
install.packages('bcmapsdata', repos='https://bcgov.github.io/drat/')
```

On my machine this works:

```
library(bcdata)
library(bcmaps)

bcdc_nr_districts <- bcdc_get_data('0bc73892-e41f-41d0-8d8e-828c16139337') 
bcmaps_nr_districts <- nr_districts()
identical(bcdc_nr_districts, bcmaps_nr_districts)
```

**Comment by bevingtona** [comment]
Thanks @boshek! Works great on my machine. 

Not sure about the good points by @stephhazlitt. `bcdata` is definitely an easier package to keep up to date because it points to the catalogue. I like `bcmaps` because many of the basemapping layers that are often needed are so quick to call. 

Thanks again for the quick fix!
