### ISSUE TITLE
Handle large layers that are on GH releases differently

### ISSUE THREAD

**Issue by ateucher** [bcgov/bcmaps#62]
Attempt to use `bcdata` to get them and cache

**Comment by boshek** [comment]
For now we are continuing to use the bcmapsdata release

**Comment by boshek** [comment]
Other options include:
- Add to bcmaps repo (☝️ maintainance)
- Download directly from WFS

**Comment by ateucher** [comment]
I think we should address this actually. Hosting the large layers on `bcmapsdata` is an albatross - the boundaries change (I know bec is in need of an update), and the process over in `bcmapsdata` is tied up into releasing the whole package. It also relies on a git workflow that I'm not certain will still work out of the box (with changes to best practices for authentication etc).

**Comment by ateucher** [comment]
Timings for downloading from WFS (I have a very fast connection):

```r
> system.time(tsa <- bcdc_get_data("8daa29da-d7f4-401c-83ae-d962e3a28980"))
   user  system elapsed 
 27.220   8.925 244.023

> system.time(bec <- bcdc_get_data("f358a53b-ffde-4830-a325-a5a03ff672c3"))
This object has 15666 records and requires 16 paginated requests to complete.
Retrieving data
  |===================================================================================| 100%
Parsing data
   user  system elapsed 
 86.032  17.948 380.226
```

**Comment by boshek** [comment]
That doesn't seem too too bad really. Is the proposal to just handle these the same as the rest of the layers?

**Comment by ateucher** [comment]
That's one of the proposals - I agree it's probably not too bad since it gets cached... I worry a bit for people with poor internet though. The major benefit is no maintenance from us, and it's always up to date. I think the other option is to bundle them into the releases in this repo rather than `bcmapsdata`.

**Comment by stephhazlitt** [comment]
I suggest we canvass the community re: internet speed and the download size -- maybe a Tweet with a reprex? We could ask colleagues in remote locations (where internet is slower) to try and report?

**Comment by ateucher** [comment]
Based on user testing in remote locations with slower/unreliable internet, we will choose option 2: move the tsa and bec functions to the same pattern as the others; i.e., a wrapper around bcdc_get_data, with caching.
